/* ══════════════════════════════════════════════════════════════
   RYS SITEWIDE SEARCH — INDEX DATA
   Titles + section headings + hand-tagged metadata only (no full
   body-text indexing). Shared by every page's nav search bar.
   ══════════════════════════════════════════════════════════════ */

window.RYS_SEARCH_INDEX = [

  /* ─── Top-level pages ─── */
  { title: "Home", url: "/", category: "Page",
    description: "Official website of Rajdhani Yuva Sansad",
    tags: ["home", "rys", "rajdhani yuva sansad", "main"] },
  { title: "About", url: "/about/", category: "Page",
    description: "Our mission, history, and the vision behind RYS",
    tags: ["about", "mission", "history", "vision", "who we are"] },
  { title: "Conferences", url: "/conferences/", category: "Page",
    description: "Browse all 24 past flagship conferences and events",
    tags: ["conferences", "events", "past", "archive", "gallery"] },
  { title: "Upcoming Conferences", url: "/upcoming/", category: "Page",
    description: "Haryana Yuva Samwad 4.0, 5.0 and the 3rd National Lawyers' Parliament Festival",
    tags: ["upcoming", "register", "registration", "next conference", "join"] },
  { title: "Contact", url: "/contact/", category: "Page",
    description: "Get in touch with the RYS team",
    tags: ["contact", "email", "phone", "reach us", "support"] },

  /* ─── Upcoming conferences (home + /upcoming/ sections) ─── */
  { title: "Haryana Yuva Samwad 4.0", url: "/upcoming/#hys-4", category: "Conference",
    description: "First Week of November 2026 · Haryana Vidhan Sabha · Nari Shakti Vandan Adhiniyam",
    tags: ["hys", "hys 4", "hys 4.0", "haryana", "haryana yuva samwad", "vidhan sabha", "women empowerment", "nari shakti", "upcoming"] },
  { title: "Haryana Yuva Samwad 5.0", url: "/upcoming/#hys-5", category: "Conference",
    description: "Middle of November 2026 · Haryana Vidhan Sabha · Environmental Protection & Sustainable Development",
    tags: ["hys", "hys 5", "hys 5.0", "haryana", "haryana yuva samwad", "vidhan sabha", "environment", "sustainability", "upcoming"] },
  { title: "3rd National Lawyers' Parliament Festival", url: "/upcoming/#nlpf-2026", category: "Conference",
    description: "28 November 2026 · Lawyers for Justice · One Nation, One Election",
    tags: ["nlpf", "lawyers parliament", "lawyers for justice", "one nation one election", "upcoming", "festival"] },
  { title: "Register — Haryana Yuva Samwad 4.0", url: "/upcoming/#hys-4-reg", category: "Section",
    description: "Free registration form for HYS 4.0", tags: ["register", "registration", "form", "hys 4"] },
  { title: "Register — Haryana Yuva Samwad 5.0", url: "/upcoming/#hys-5-reg", category: "Section",
    description: "Free registration form for HYS 5.0", tags: ["register", "registration", "form", "hys 5"] },
  { title: "Register — National Lawyers' Parliament Festival", url: "/upcoming/#nlpf-reg", category: "Section",
    description: "Free registration form for NLPF 2026", tags: ["register", "registration", "form", "nlpf"] },

  /* ─── Home-page sections ─── */
  { title: "The Founders", url: "/#founders", category: "Section",
    description: "Adv. Isha Kapoor & Adv. Jai Saini — Co-Founders, RYS",
    tags: ["founders", "isha kapoor", "jai saini", "about", "team", "co-founders"] },
  { title: "Rajdhani Changemakers Foundation", url: "/#founders", category: "Section",
    description: "RYS is an entity of Rajdhani Changemakers Foundation",
    tags: ["changemakers", "foundation", "parent organisation", "entity"] },
  { title: "Our Partners & Collaborators", url: "/#sponsors-sec", category: "Section",
    description: "Esteemed dignitaries and institutional partners", tags: ["partners", "sponsors", "collaborators", "dignitaries"] },
  { title: "Join the Next National Dialogue", url: "/#cta-band", category: "Section",
    description: "Join RYS and be part of the movement", tags: ["join", "join us", "cta", "membership"] },

  /* ─── Past conferences (24) ─── */
  { title: "Bal Sansad 1.0", url: "/conferences/bal_sansad_1/", category: "Conference",
    description: "Nurturing tomorrow's leaders from an early age", tags: ["bal sansad", "children parliament", "school"] },
  { title: "Bal Sansad 2.0", url: "/conferences/bal_sansad_2/", category: "Conference",
    description: "Second edition of the children's parliament", tags: ["bal sansad", "children parliament", "school"] },
  { title: "Mock Lok Sabha — Bal Bharti Noida", url: "/conferences/bal_bharti_noida/", category: "Conference",
    description: "Mock Lok Sabha simulation at Bal Bharti Public School, Noida", tags: ["mock lok sabha", "bal bharti", "noida", "school"] },
  { title: "Delhi Yuva Samvad 2024", url: "/conferences/delhi_yuva_samvad_2024/", category: "Conference",
    description: "Youth dialogue conference in Delhi, 2024", tags: ["delhi yuva samvad", "delhi", "2024"] },
  { title: "Global Panchayat 1.0", url: "/conferences/global_panchayat_1/", category: "Conference",
    description: "First edition of the Global Panchayat conference", tags: ["global panchayat", "panchayat"] },
  { title: "Global Panchayat 2.0", url: "/conferences/global_panchayat_2/", category: "Conference",
    description: "Second edition of the Global Panchayat conference", tags: ["global panchayat", "panchayat"] },
  { title: "Global Panchayat 3.0", url: "/conferences/global_panchayat_3/", category: "Conference",
    description: "Third edition of the Global Panchayat conference", tags: ["global panchayat", "panchayat"] },
  { title: "Gorakhpur Yuva Samvad 2025", url: "/conferences/gorakhpur_yuva_samvad_2025/", category: "Conference",
    description: "Youth dialogue conference in Gorakhpur, 2025", tags: ["gorakhpur", "yuva samvad", "2025"] },
  { title: "Haryana Yuva Samwad 2025", url: "/conferences/haryana_yuva_samvad_2025/", category: "Conference",
    description: "Haryana Yuva Samwad, 2025 edition (past)", tags: ["haryana yuva samwad", "hys", "2025", "haryana"] },
  { title: "Haryana Yuva Samwad 2026", url: "/conferences/haryana_yuva_samvad_2026/", category: "Conference",
    description: "Haryana Yuva Samwad, 2026 edition", tags: ["haryana yuva samwad", "hys", "2026", "haryana"] },
  { title: "HP Academy Gorakhpur Training Sessions", url: "/conferences/hp_academy_gorakhpur/", category: "Conference",
    description: "Training sessions held at HP Academy, Gorakhpur", tags: ["hp academy", "gorakhpur", "training"] },
  { title: "Ideas in Action Summit 1.0", url: "/conferences/ideas_in_action_summit_1/", category: "Conference",
    description: "First edition of the Ideas in Action Summit", tags: ["ideas in action", "summit"] },
  { title: "Mahila Yuva Samwad 2026", url: "/conferences/mahila_yuva_samwad_2026/", category: "Conference",
    description: "Women's youth dialogue conference, 2026", tags: ["mahila yuva samwad", "women", "gender", "2026"] },
  { title: "1st National Lawyers' Parliament Festival 2023", url: "/conferences/nlpf_2023/", category: "Conference",
    description: "First edition of the National Lawyers' Parliament Festival", tags: ["nlpf", "lawyers parliament", "2023"] },
  { title: "2nd National Lawyers' Parliament Festival 2024", url: "/conferences/nlpf_2024/", category: "Conference",
    description: "Second edition of the National Lawyers' Parliament Festival", tags: ["nlpf", "lawyers parliament", "2024"] },
  { title: "Sajag Yuva Manch 1.0", url: "/conferences/sajag_yuva_manch_1/", category: "Conference",
    description: "First edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Sajag Yuva Manch 2.0", url: "/conferences/sajag_yuva_manch_2/", category: "Conference",
    description: "Second edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Sajag Yuva Manch 3.0", url: "/conferences/sajag_yuva_manch_3/", category: "Conference",
    description: "Third edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Sajag Yuva Manch 4.0", url: "/conferences/sajag_yuva_manch_4/", category: "Conference",
    description: "Fourth edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Sajag Yuva Manch 5.0", url: "/conferences/sajag_yuva_manch_5/", category: "Conference",
    description: "Fifth edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Sajag Yuva Manch 6.0", url: "/conferences/sajag_yuva_manch_6/", category: "Conference",
    description: "Sixth edition of Sajag Yuva Manch", tags: ["sajag yuva manch", "yuva manch"] },
  { title: "Mock Lok Sabha — Salwan Gurugram", url: "/conferences/salwan_gurugram/", category: "Conference",
    description: "Mock Lok Sabha simulation at Salwan Public School, Gurugram", tags: ["mock lok sabha", "salwan", "gurugram", "school"] },
  { title: "RYS Conference — St. Xavier's Delhi", url: "/conferences/st_xaviers_delhi/", category: "Conference",
    description: "RYS conference held at St. Xavier's School, Delhi", tags: ["st xaviers", "xavier", "delhi", "school"] },
  { title: "Yuva Sajhedari 1.0", url: "/conferences/yuva_sajhedari_1/", category: "Conference",
    description: "First edition of Yuva Sajhedari", tags: ["yuva sajhedari", "sajhedari"] },
  { title: "Yuva Sajhedari 2.0", url: "/conferences/yuva_sajhedari_2/", category: "Conference",
    description: "Second edition of Yuva Sajhedari", tags: ["yuva sajhedari", "sajhedari"] }
];
